### ISSUE TITLE
enum34 requirement causes problems on Python 3.4+

### ISSUE THREAD

**Issue by genderquery** [xmikos/reparser#1] opened 2015-08-13 11:40 UTC
I was having the same issue described here: https://github.com/opentok/Opentok-Python-SDK/pull/70

It appears to be a conflict between enum34-1.0.4 and stdlib in Python 3.4+. I was able to fix this by removing enum34 requirement in setup.py.

**Comment by tdryer** [comment] 2015-08-27 03:31
To add some context, the issue is that Python 3.5 will include an updated enum module that the standard library requires, so using the version from 3.4 will break things.

Since hangups requires reparser, it won't work with Python 3.5 until this is patched.

**Comment by xmikos** [comment] 2015-08-27 05:15
I will fix it today, thanks for info and sorry for the delay.

**Comment by jtamagnan** [comment] 2015-09-04 19:26
Since genderquery made the necessary changes in a fork, would it be safe to say that we can close this issue?

**Comment by xmikos** [comment] 2015-09-04 20:51
I have merged it and released new version 1.4.3. It is already published on PyPI too.
Sorry that it took that long :-(

**Closed as completed by xmikos** 2015-09-04 20:51 UTC
